name: Can workflows in sub directories be found

description: Turns out they cannot :(

on:
  workflow_dispatch:

jobs:
  yes:
    runs-on: ubuntu-latest
    steps:
      - name: Yes
        run: echo 'yes they can!'
