name: Act Artifacts

description: |
  When using artificats with Act, you must set the `artifact-server-path` to something.
  Here I have set it to `$PWD/.artifacts`.

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello mung' > mung.txt
      - uses: actions/upload-artifact@v4
        with:
          name: mung
          path: mung.txt
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mung
          path: .
      - run: cat mung.txt
