name: Matrix Outputs

description: Testing how to handle outputs from matrix jobs

on:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [a, b, c]
        b: [1, 2, 3]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-write@v1
        with:
          matrix-step-name: result
          matrix-key: ${{ matrix.a }}-${{ matrix.b }}
          outputs: | # yaml
            thing: ${{ matrix.a }}/${{ matrix.b }}

  log:
    runs-on: ubuntu-latest
    needs: [matrix]
    steps:
      - id: read
        uses: cloudposse/github-action-matrix-outputs-read@v1
        with:
          matrix-step-name: result
      - run: echo '${{ steps.read.outputs.result }}' >> $GITHUB_STEP_SUMMARY
  