name: Matrix Filtering

description: Testing how to "filter", or pre-emptively "continue" when using matrixes

on:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        a: [a, b]
        b: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: is even
        id: test
        run: | # shell
          var=${{ matrix.b }}
          if [[ $((var % 2)) -eq 0 ]]
          then 
            echo "$var is even"
          else
            echo "$var is odd"
            exit 1
          fi

      - if: failure()
        run: echo "::notice title=Skipping::Skipping ${{ matrix.b }} as it is not even

      - run: echo "${{ matrix.a }}/${{ matrix.b }}" >> $GITHUB_STEP_SUMMARY

  post-matrix:
    needs: [matrix]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!" >> $GITHUB_STEP_SUMMARY
