# Testing what it outputted from a matrix job

name: Matrix Outputs

on:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [a, b, c]
        b: [1, 2, 3]
    steps:
      - run: | # shell
          mkdir -p outputs
          echo "${{ matrix.a }}/${{ matrix.b }}" >> outputs/${{ matrix.a }}.${{ matrix.b }}.txt

      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/*.txt

  log:
    runs-on: ubuntu-latest
    needs: [matrix]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: outputs
          path: outputs

      - run: cat outputs/*.txt >> $GITHUB_STEP_SUMMARY
  